"""init tables

Revision ID: 02216441cc09
Revises: 
Create Date: 2025-10-01 17:23:10.392610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02216441cc09'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('marks', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.alter_column('students', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.create_index(op.f('ix_students_name'), 'students', ['name'], unique=False)
    op.create_foreign_key(None, 'students', 'teachers', ['teacher_id'], ['id'])
    op.drop_column('students', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_index(op.f('ix_students_name'), table_name='students')
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.alter_column('students', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('students', 'teacher_id')
    op.drop_column('students', 'marks')
    # ### end Alembic commands ###
